name: Aider PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Aider and GitHub CLI
        run: |
          python -m pip install --upgrade pip
          pip install aider-chat

      - name: Configure GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Get PR diff and create review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the diff
          git fetch origin ${{ github.base_ref }}
          git diff origin/${{ github.base_ref }}...HEAD > pr_diff.txt
          
          # Create a message file for aider
          echo "Please review this PR diff and provide feedback. Focus on code quality, potential bugs, and suggested improvements:" > message.txt
          cat pr_diff.txt >> message.txt
          
          # Run aider with non-interactive flags
          aider --model gpt-4 \
                --message-file message.txt \
                --no-git \
                --no-auto-commits \
                --yes-always \
                --no-pretty \
                --no-stream > review.txt
          
          # Format the review for GitHub
          echo "## AI Code Review" > formatted_review.txt
          echo "\`\`\`" >> formatted_review.txt
          cat review.txt >> formatted_review.txt
          echo "\`\`\`" >> formatted_review.txt
          
          # Post the review as a PR comment
          gh pr comment ${{ github.event.pull_request.number }} --body-file formatted_review.txt
